import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Nav } from "../components/nav";
import { Analytics } from "@vercel/analytics/react";
import { cn } from "@/lib/utils";

const inter = localfont({
  src: "../fonts/InterVariable.woff2",
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <div>{children}</div>
        <Toaster />
      </body>
      <Analytics />
      {modal}
    </html>
  );
}
