import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import { Nav } from "./components/nav";

const wanted = localfont({
  src: [
    {
      path: "../fonts/WantedSansVariable.woff2",
    },
  ],
  display: "swap",
  variable: "--font-sans",
});

const pretendard = localfont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-sans",
});

const inter = localfont({
  src: [
    {
      path: "../fonts/InterVariable.woff2",
    },
    {
      path: "../fonts/InterVariable-italic.woff2",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={wanted.className}>{children}</body>
    </html>
  );
}
